Ninja-Squad/globe42

README.md, backend/build.gradle, backend/src/main/java/org/globe42/web/security/JwtHelper.java, backend/src/test/java/org/globe42/CrypticApplicationTest.java, backend/src/test/java/org/globe42/dao/BaseDaoTest.java, backend/src/test/java/org/globe42/web/security/JwtHelperTest.java, backend/src/test/resources/test.properties
Also fix the DAO tests and renamed the main test.
Since the repo is public, we don't want to expose the actual secret key used to generate tokens. We also might want to change it fast, without having to redeploy.
So the key is now externalized. What this means is that
- integration tests that use a non-mocked JwtHelper bean must add the `globe42.secretKey` to their environment. That is easily done using the test.properties file. See `CrypticApplicationTest` for an example.
- run configurations that start the application must define this property, too. This can be done using an environment variable or a command-line argument: `
--globe42.secretKey=QMwbcwa19VV02Oy5T7LSWyV+/wZrOsRRfhCR6TkapsY=`
- when deployed in production, we'll have to do the same thing. Alternatives are described in …
=> feat(security): externalize secret key

frontend/build.gradle, frontend/package.json
Besides the advantage of having coverage information, this is also useful to make sure the frontend tests are rerun after a clean. Indeed, since the test task had no output, tests were not rerun after a clean if the test task inputs had not changed, which is a bit surprising.
=> build: add test coverage to frontend

README.md, backend/src/main/resources/application.yml, backend/src/main/resources/demo/db/migration/V0004__user_insert.sql
I didn't find a data file with the admin user (as explained in Slack), so I've used the PasswordDigesterTest to generate the data for the user admin and I added these data in a file under the backend/src/main/resources/db.migration directory
Such a user is mandatory to dev/test the application and do the demo
=> add user admin (dev)

backend/src/main/java/org/globe42/dao/UserDao.java, backend/src/main/java/org/globe42/web/security/AuthenticatedUserDTO.java, backend/src/main/java/org/globe42/web/security/AuthenticationController.java, backend/src/main/java/org/globe42/web/users/ChangePasswordCommandDTO.java, backend/src/main/java/org/globe42/web/users/PasswordGenerator.java, backend/src/main/java/org/globe42/web/users/UserCommandDTO.java, backend/src/main/java/org/globe42/web/users/UserController.java, backend/src/main/java/org/globe42/web/users/UserDTO.java, backend/src/main/java/org/globe42/web/users/UserWithPasswordDTO.java, backend/src/test/java/org/globe42/dao/UserDaoTest.java, backend/src/test/java/org/globe42/web/incomes/IncomeSourceTypeControllerTest.java, backend/src/test/java/org/globe42/web/security/AuthenticationControllerTest.java, backend/src/test/java/org/globe42/web/users/PasswordGeneratorTest.java, backend/src/test/java/org/globe42/web/users/UserControllerMvcTest.java, backend/src/test/java/org/globe42/web/users/UserControllerTest.java
The user model is limited to login for now, but it will probably contain roles and maybe email in the future.
The intended usage of the API is that an admin creates a user, gets the automatically generated password and gives the login and password to the actual user, which is then free to change his password.
We could imagine storing a flag indicating that the password is auto-generated and force the user to change it, but it's probably useless, since the admin can reset the password anyway, and thus act as the other users.
=> feat(users): add CRUD services for users, and password resets/changes

backend/src/main/java/org/globe42/web/exception/BadRequestException.java, backend/src/main/java/org/globe42/web/exception/ErrorCode.java, backend/src/main/java/org/globe42/web/exception/ExceptionConfig.java, backend/src/main/java/org/globe42/web/exception/FunctionalError.java, backend/src/main/java/org/globe42/web/incomes/IncomeSourceController.java, backend/src/main/java/org/globe42/web/incomes/IncomeSourceTypeController.java, backend/src/main/java/org/globe42/web/users/UserController.java, backend/src/test/java/org/globe42/web/exception/BadRequestExceptionTest.java, backend/src/test/java/org/globe42/web/exception/ExceptionConfigTest.java, frontend/src/app/app.component.html, frontend/src/app/app.module.ts, frontend/src/app/error.service.spec.ts, frontend/src/app/error.service.ts, frontend/src/app/error/error.component.html, frontend/src/app/error/error.component.scss, frontend/src/app/error/error.component.spec.ts, frontend/src/app/error/error.component.ts, frontend/src/app/income-source-edit/income-source-edit.component.ts, frontend/src/app/income-type-edit/income-type-edit.component.html, frontend/src/app/income-type-edit/income-type-edit.component.ts, frontend/src/app/jwt-interceptor.service.spec.ts, frontend/src/app/models/error.model.ts, frontend/src/app/person-income-edit/person-income-edit.component.ts, frontend/src/app/user-edit/user-edit.component.ts, frontend/src/app/users/users.component.ts, frontend/src/app/utils.spec.ts, frontend/src/app/utils.ts
This is an exploratory WIP to test what I think we should do to fix #47.
Please tell me what you think about it.
In fact I think I would prefer to let the interceptor handle all the errors, even the functional ones, but in some use cases, the default behavior would not be adequate (that could also be true with technical errors, BTW). It would really be nice if https://github.com/angular/angular/issues/18155 was accepted and fixed.
In the meantime, I'm sure we could find a workaround solution.
The various kinds of errors can be tested the following way:
- stop the ng server, and try navigating: technical error without a http response
- stop the backend server: technical error response sent by the ng server
- try to create a user with a login that already exists: functional error
=> Feat/errors (WIP)

.travis.yml, frontend/karma.conf.js, frontend/package.json, frontend/yarn.lock
This uses [bundlesize](https://github.com/siddharthkp/bundlesize) to add a check on Travis about the bundle sizes (gzipped).
@jnizet This requires you to add a specific env variable on travis, check Slack for mre details.
=> chore: check js bundle sizes on buil

frontend/src/app/current-user/current-user.service.spec.ts, frontend/src/app/current-user/current-user.service.ts
Scenario when it failed:
1. Login: the remember me local storage item and the cookie are stored
2. Access a file: we need a cookiefor that because it's not an AJAX request. Everything works fine because the cookie is there.
3. Close the browser
4. Reopen the browser: the local storage item is still there, but the cookie is not
5. Access a file: failure due to the absence of cookie
The cookie is now recreated at startup if the local storage item is there. So the above scenario should now work fine.
=> fix: a re-login is not needed anymore to access files

.travis.yml, backend/build.gradle
This should be temporary, bacause clever cloud should migrate to PosgreSQL 10 in 1 or 2 months.
Also use version 9.2 on TravisCI, in order to test that everything works fine with the database we actually use in production.
=> chore: downgrade flyway because version 5+ doesn't support postgresql 9.2

README.md, backend/src/main/java/org/globe42/storage/StorageConfig.java, backend/src/main/java/org/globe42/storage/StorageProperties.java
This is cleaner than using @Value.
Note that even though the properties must be in lower case with dashes
when reading them, then can be written in camelCase in the yaml file
or in the command-line parameters or environment variables.
Also note that, to be cleaner, I changed the name of the properties:
`globe42.googleCloudStorageCredentials` becomes
`globe42.googleCloudStorage.credentials`, and
`globe42.googleCloudStorageCredentialsPath` becomes
`globe42.googleCloudStorage.credentialsPath`.
In order to avoid forgetting to change the environment when deploying
this new version, I already added the new environment variable in the
Clever Cloud console. We'll just have to remove the old variable when
this change is deployed.
=> refactor: use a StorageProperties class to load the GCS properties

frontend/tslint.json
Adds a few rules:
- angular-whitespace (removed check-pipe as it has a bug with this project)
- banana-in-box
- contextual-life-cycle
- templates-no-negated-async
- template-conditional-complexity
- use-view-encapsulation
I did not add template-cyclomatic-complexity, as it needs a high threshold (25) to pass due to the forms template
that contains a high number of `ngIf`.
=> chore(lint): add codelyzer rules

backend/build.gradle.kts, frontend/build.gradle.kts
- add a missing dependency
- use yarn rather than npm to run scripts
- remove moment locales after yarn install, since they're useless and take 60KB of the bundle
- configure the frontend assemble task and use it as a dependency in the backend
- use references to tasks rather than strings
=> build: improvements

frontend/src/app/person-charge-edit/person-charge-edit.component.spec.ts, frontend/src/app/person-charge-edit/person-charge-edit.component.ts, frontend/src/app/person-income-edit/person-income-edit.component.spec.ts, frontend/src/app/person-income-edit/person-income-edit.component.ts
the validation was not triggered when another field was modified,
although the validator result depends on this other field value.
=> fix: fix validation bug

frontend/angular.json
CLI 6.0.7 added a prod config for e2e
See https://github.com/cexbrayat/angular-cli-diff/compare/6.0.5...6.0.7
=> chore(deps): cli conf

frontend/.gitignore, frontend/build.gradle.kts, frontend/package.json, frontend/src/app/page-title.directive.ts
=> build: fix bug, add lint in check

frontend/src/app/participants/participants.component.ts, frontend/src/app/person-files/person-files.component.ts, frontend/src/app/spent-time-statistics/spent-time-statistics.component.ts, frontend/src/app/task.service.ts, frontend/src/app/utils.spec.ts, frontend/src/app/utils.ts
This isn't really needed, but I wanted to experiment, and having `.reversed()` rather than `true` makes the code clearer
=> refactor: improve the way arrays are sorted, allow multiple sort criteria

frontend/src/app/confirm.service.spec.ts, frontend/src/app/confirm.service.ts, frontend/src/app/person-family/person-family.component.spec.ts, frontend/src/app/person-family/person-family.component.ts, frontend/src/app/person-network-members/person-network-members.component.spec.ts, frontend/src/app/person-network-members/person-network-members.component.ts, frontend/src/app/person-note-edition.guard.spec.ts, frontend/src/app/person-note-edition.guard.ts, frontend/src/app/person-notes/person-notes.component.spec.ts, frontend/src/app/person-notes/person-notes.component.ts, frontend/src/app/person-resources/person-resources.component.spec.ts, frontend/src/app/person-resources/person-resources.component.ts, frontend/src/app/person-wedding-events/person-wedding-events.component.spec.ts, frontend/src/app/person-wedding-events/person-wedding-events.component.ts, frontend/src/app/person/person.component.spec.ts, frontend/src/app/person/person.component.ts, frontend/src/app/users/users.component.spec.ts, frontend/src/app/users/users.component.ts
Instead of emitting an error on close, which forces every caller to use an error callback in order to avoid an error in tests and in the browser console, the observable simply completes without emitting any event.
This makes the nominal case simpler.
If the caller wants to be notified when closed (like in a CanDeactivate guard), then the caller can pass `errorOnClose: true` in the confirm options.
=> refactor: improve confirm service

frontend/src/app/app.component.html, frontend/src/app/app.module.ts, frontend/src/app/menu/menu.component.html, frontend/src/app/navigation-progress/navigation-progress.component.html, frontend/src/app/navigation-progress/navigation-progress.component.scss, frontend/src/app/navigation-progress/navigation-progress.component.spec.ts, frontend/src/app/navigation-progress/navigation-progress.component.ts
To test what it looks like, load the app then set the network speed to slow 3G in the network panel of the chrome dev tools.
@cexbrayat I'd like your advice on 3 things here:
1. This is really cool (IMHO), but only works because each and every page uses a resolver to load its data. Do you have any idea how we could achieve the same thing without resolvers?
2. I don't like the hack of shifting the values by 1 just to be able to use `*ngIf="value$ as async"`. I would prefer using something like  `*ngIf="(value$ as async) !== null"` but that doesn't seem possible.
3. During the navigation, this forces a global change detection every 500ms, although I know that the only thing that should change is the naigtaion progress component itself. Is there anything we can do to limit the scope of the …
=> feat: add a thin github-like navigation progress bar at the top

backend/src/test/java/org/globe42/test/GlobeMvcTest.java, backend/src/test/kotlin/org/globe42/CrypticApplicationTest.kt, backend/src/test/kotlin/org/globe42/dao/BaseDaoTest.kt, backend/src/test/kotlin/org/globe42/web/security/AdminOnlyIntegrationTest.kt, backend/src/test/kotlin/org/globe42/web/security/AuthenticationTest.kt
- avoid using unnecessary ExtendWith annotation (since XxxTest is already annotated with it)
- make AdminOnlyIntegrationTest faster by only loading a tiny context instead of the whole context
=> refactor: improve tests

frontend/src/app/globe-validators.ts
This is breaking when trying to build with v8/Ivy
=> fix: unnecessary deep import

frontend/angular.json, frontend/extra-webpack.config.js, frontend/package.json, frontend/src/app/chart/chart.component.spec.ts, frontend/src/app/health-care-coverage/health-care-coverage.component.spec.ts, frontend/src/app/health-care-coverage/health-care-coverage.component.ts, frontend/src/app/spent-time-statistics/spent-time-statistics.component.spec.ts, frontend/src/app/spent-time-statistics/spent-time-statistics.component.ts, frontend/yarn.lock
This allows
- getting rid of its separate typings, since they're now provided with chart.js
- getting rid of the custom webpack builder, because we don't need to remove moment anymore
I was expecting a decrease of the bundle size too, given that chart.js 3.x is tree-shakeable, but that doesn't seem to be the case, I don't know why.
=> chore: upgrade to chart.js 3.0.0-beta.7

.circleci/config.yml, frontend/.gitignore, frontend/build.gradle.kts, frontend/package.json
- avoid relying on automatic rules, and instead define tasks explicitly for less magic;
- use the default yarn task instead of redefining one;
- move reports to build dir
=> build: upgrade node plugin and improve frontend build

.circleci/config.yml
```
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.6' to '10.10'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
N: This must be accepted …
```
=> ci: add flag to apt-get in hope to fix issue
