Ninja-Squad/globe42

- frontend/build.gradle
- frontend/package.json
the gradle build now also runs the frontend tests
fix #15
> build: add test task to frontend

- backend/build.gradle
- backend/src/main/java/org/globe42/dao/IncomeDao.java
- backend/src/main/java/org/globe42/dao/IncomeSourceDao.java
- backend/src/main/java/org/globe42/dao/IncomeSourceTypeDao.java
- backend/src/main/java/org/globe42/domain/Income.java
- backend/src/main/java/org/globe42/domain/IncomeSource.java
- backend/src/main/java/org/globe42/domain/IncomeSourceType.java
- backend/src/main/java/org/globe42/domain/Person.java
- backend/src/main/resources/db/migration/V0001__init.sql
- backend/src/main/resources/db/migration/V0002__user.sql
- backend/src/main/resources/db/migration/V0003__income.sql
- backend/src/test/java/org/globe42/dao/BaseDaoTest.java
- backend/src/test/java/org/globe42/dao/PersonDaoTest.java
- backend/src/test/java/org/globe42/dao/UserDaoTest.java
Also
- improve the naming in SQL files and in DAO tests.
- remove unusable flyway tasks added by the plugin
> feat(income): add income and related entities

- backend/src/main/java/org/globe42/dao/PostalCityDao.java
- backend/src/main/java/org/globe42/dao/PostalCityDaoCustom.java
- backend/src/main/java/org/globe42/dao/PostalCityDaoImpl.java
- backend/src/main/java/org/globe42/domain/PostalCity.java
- backend/src/main/java/org/globe42/web/cities/PostalCityController.java
- backend/src/main/java/org/globe42/web/cities/PostalCityUploadParser.java
- backend/src/main/java/org/globe42/web/persons/CityDTO.java
- backend/src/main/resources/db/migration/V0009__postal_city.sql
- backend/src/test/java/org/globe42/dao/BaseDaoTest.java
- backend/src/test/java/org/globe42/dao/PostalCityDaoTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityControllerMvcTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityControllerTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityUploadParserTest.java
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/cities-upload/cities-upload.component.html
- frontend/src/app/cities-upload/cities-upload.component.spec.ts
- frontend/src/app/cities-upload/cities-upload.component.ts
- frontend/src/app/search-city.service.spec.ts
- frontend/src/app/search-city.service.ts
- frontend/src/custom-bootstrap.scss
- frontend/src/index.html
- frontend/yarn.lock
> Chore/cli 1.2.4

- .travis.yml
- backend/build.gradle
- backend/src/main/java/org/globe42/dao/PostalCityDao.java
- backend/src/main/java/org/globe42/dao/PostalCityDaoCustom.java
- backend/src/main/java/org/globe42/dao/PostalCityDaoImpl.java
- backend/src/main/java/org/globe42/domain/PostalCity.java
- backend/src/main/java/org/globe42/web/MaxAgeCacheConfig.java
- backend/src/main/java/org/globe42/web/cities/PostalCityController.java
- backend/src/main/java/org/globe42/web/cities/PostalCityUploadParser.java
- backend/src/main/java/org/globe42/web/persons/CityDTO.java
- backend/src/main/resources/db/migration/V0009__postal_city.sql
- backend/src/test/java/org/globe42/dao/BaseDaoTest.java
- backend/src/test/java/org/globe42/dao/PostalCityDaoTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityControllerMvcTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityControllerTest.java
- backend/src/test/java/org/globe42/web/cities/PostalCityUploadParserTest.java
- frontend/build.gradle
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/cities-upload/cities-upload.component.html
- frontend/src/app/cities-upload/cities-upload.component.spec.ts
- frontend/src/app/cities-upload/cities-upload.component.ts
- frontend/src/app/search-city.service.spec.ts
- frontend/src/app/search-city.service.ts
- frontend/src/custom-bootstrap.scss
- frontend/src/index.html
- frontend/yarn.lock
See https://docs.travis-ci.com/user/languages/java/#Caching
and https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Caching-with-yarn
> build: cache yarn and gradle deps

- .codecov.yml
- .travis.yml
- backend/build.gradle
- frontend/package.json
- frontend/yarn.lock
This is an attempt to have codecoverage reports for both the backend and the frontend.
> build: add codecoverage report with codecov.io

- backend/src/main/java/org/globe42/web/tasks/TaskController.java
- backend/src/test/java/org/globe42/web/tasks/TaskControllerTest.java
- frontend/src/app/task.service.spec.ts
- frontend/src/app/task.service.ts
- frontend/src/app/tasks-page/tasks-page.component.spec.ts
- frontend/src/app/tasks-page/tasks-page.component.ts
- frontend/src/app/tasks/tasks.component.html
- frontend/src/app/tasks/tasks.component.spec.ts
- frontend/src/app/tasks/tasks.component.ts
A little contribution, to understand a bit better how it works.
👍 design, really easy to add a feature.
> feat(tasks): unassign a task

- frontend/src/app/person/person.component.html
- frontend/src/app/task-edit/task-edit.component.html
- frontend/src/app/tasks-layout/tasks-layout.component.html
- frontend/src/app/tasks/tasks.component.scss
- frontend/src/styles.scss
- add margins in person page
- fix min date on task due date edition
- allow text wrapping on new task link to avoid text overflow
> fix: revert global margin before h2 because it's painful in general

- frontend/src/app/globe-ngb/globe-ngb.module.ts
the previous one removes all default values for other properties
> fix: customization of datepicker

- frontend/src/app/globe-ngb/globe-ngb.module.ts
- frontend/src/app/globe-ngb/non-editable-typeahead.directive.ts
- frontend/src/app/person-edit/person-edit.component.html
- frontend/src/app/person/person-typeahead.ts
- frontend/src/app/task-edit/task-edit.component.html
- frontend/src/app/task-edit/task-edit.component.ts
also sort persons in typeaheads, and fix a linting issue
> refactor: add a directive to help with tyeaheads

- frontend/src/app/task-edit/task-edit.component.html
> feat: move task category in first position in the task edit page

- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/person-note-edition.guard.spec.ts
- frontend/src/app/person-note-edition.guard.ts
- frontend/src/app/person-notes/person-notes.component.spec.ts
- frontend/src/app/person-notes/person-notes.component.ts
- frontend/src/app/person/person.component.html
- frontend/src/app/person/person.component.ts
> feat: warn if leaving person page with note being edited

- backend/src/main/java/org/globe42/dao/TaskDao.java
- backend/src/main/java/org/globe42/web/tasks/TaskController.java
- backend/src/test/java/org/globe42/dao/TaskDaoTest.java
- backend/src/test/java/org/globe42/web/tasks/TaskControllerMvcTest.java
- backend/src/test/java/org/globe42/web/tasks/TaskControllerTest.java
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/person-tasks/person-tasks.component.html
- frontend/src/app/person-tasks/person-tasks.component.spec.ts
- frontend/src/app/person-tasks/person-tasks.component.ts
- frontend/src/app/task.service.spec.ts
- frontend/src/app/task.service.ts
- frontend/src/app/tasks-resolver.service.spec.ts
- frontend/src/app/tasks-resolver.service.ts
> feat: display archived tasks for a person, in a separate tab

- backend/src/main/java/org/globe42/domain/Person.java
- backend/src/main/java/org/globe42/web/persons/PersonCommandDTO.java
- backend/src/main/java/org/globe42/web/persons/PersonController.java
- backend/src/main/java/org/globe42/web/persons/PersonDTO.java
- backend/src/main/resources/db/migration/V0023__fical_number.sql
- backend/src/test/java/org/globe42/domain/PersonTest.java
- backend/src/test/java/org/globe42/web/persons/PersonControllerTest.java
- frontend/src/app/models/person.command.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person-edit/person-edit.component.html
- frontend/src/app/person-edit/person-edit.component.spec.ts
- frontend/src/app/person-edit/person-edit.component.ts
- frontend/src/app/person/person.component.html
- frontend/src/app/person/person.component.spec.ts
> feat: add fiscal number to person, remove fiscal status date

- frontend/src/app/charge-categories/charge-categories.component.html
- frontend/src/app/charge-category-edit/charge-category-edit.component.html
- frontend/src/app/charge-category-edit/charge-category-edit.component.spec.ts
- frontend/src/app/charge-type-edit/charge-type-edit.component.html
- frontend/src/app/charge-type-edit/charge-type-edit.component.spec.ts
- frontend/src/app/charge-types/charge-types.component.html
- frontend/src/app/home/home.component.html
- frontend/src/app/income-source-edit/income-source-edit.component.html
- frontend/src/app/income-source-edit/income-source-edit.component.spec.ts
- frontend/src/app/income-sources/income-sources.component.html
- frontend/src/app/income-type-edit/income-type-edit.component.html
- frontend/src/app/income-type-edit/income-type-edit.component.spec.ts
- frontend/src/app/income-types/income-types.component.html
- frontend/src/app/menu/menu.component.html
- frontend/src/app/person-charge-edit/person-charge-edit.component.html
- frontend/src/app/person-income-edit/person-income-edit.component.html
> chore: rename charge/income labels

- backend/src/main/java/org/globe42/domain/Person.java
- backend/src/main/java/org/globe42/domain/WeddingEvent.java
- backend/src/main/java/org/globe42/domain/WeddingEventType.java
- backend/src/main/java/org/globe42/web/persons/WeddingEventCommandDTO.java
- backend/src/main/java/org/globe42/web/persons/WeddingEventController.java
- backend/src/main/java/org/globe42/web/persons/WeddingEventDTO.java
- backend/src/main/resources/db/migration/V0026__wedding_event.sql
- backend/src/test/java/org/globe42/web/persons/WeddingEventControllerMvcTest.java
- backend/src/test/java/org/globe42/web/persons/WeddingEventControllerTest.java
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/display-wedding-event-type.pipe.spec.ts
- frontend/src/app/display-wedding-event-type.pipe.ts
- frontend/src/app/models/wedding-event.command.ts
- frontend/src/app/models/wedding-event.model.ts
- frontend/src/app/person-layout/person-layout.component.html
- frontend/src/app/person-layout/person-layout.component.spec.ts
- frontend/src/app/person-wedding-events/person-wedding-events.component.html
- frontend/src/app/person-wedding-events/person-wedding-events.component.spec.ts
- frontend/src/app/person-wedding-events/person-wedding-events.component.ts
- frontend/src/app/wedding-event.service.spec.ts
- frontend/src/app/wedding-event.service.ts
- frontend/src/app/wedding-events-resolver.service.spec.ts
- frontend/src/app/wedding-events-resolver.service.ts
> feat(person): store wedding and divorce dates

- backend/src/main/java/org/globe42/domain/FamilySituation.java
- backend/src/main/java/org/globe42/web/persons/FamilySituationDTO.java
- backend/src/main/java/org/globe42/web/persons/PersonController.java
- backend/src/main/resources/db/migration/V0027__remove_sibling_count.sql
- backend/src/test/java/org/globe42/web/persons/PersonControllerTest.java
- frontend/src/app/family-situation-edit/family-situation-edit.component.html
- frontend/src/app/family-situation-edit/family-situation-edit.component.spec.ts
- frontend/src/app/family-situation/family-situation.component.html
- frontend/src/app/family-situation/family-situation.component.spec.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person-edit/person-edit.component.spec.ts
> feat(person): remove sibling count

- backend/src/main/kotlin/org/globe42/domain/HealthCareCoverage.kt
- backend/src/main/kotlin/org/globe42/domain/HealthInsurance.kt
- backend/src/main/kotlin/org/globe42/domain/Person.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonCommandDTO.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonDTO.kt
- backend/src/main/resources/db/migration/V0029__update_health_care_coverage_and_insurance.sql
- backend/src/test/kotlin/org/globe42/dao/PersonDaoTest.kt
- backend/src/test/kotlin/org/globe42/dao/TaskDaoTest.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerTest.kt
- frontend/src/app/app.module.ts
- frontend/src/app/display-health-care-coverage.pipe.spec.ts
- frontend/src/app/display-health-care-coverage.pipe.ts
- frontend/src/app/display-health-insurance.pipe.spec.ts
- frontend/src/app/display-health-insurance.pipe.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person-edit/person-edit.component.html
- frontend/src/app/person-edit/person-edit.component.spec.ts
- frontend/src/app/person-edit/person-edit.component.ts
- frontend/src/app/person/person.component.html
- frontend/src/app/person/person.component.spec.ts
relative to #175 (part of the health care coverage and health insurance).
WIP : I have to add an SQL script
> feat : update health care coverage and health insurance

- frontend/package.json
- frontend/src/app/person-edit/person-edit.component.spec.ts
- frontend/src/app/task-edit/task-edit.component.spec.ts
- frontend/yarn.lock
This demonstrates the usage of https://github.com/Ninja-Squad/ngx-fixture/pull/1
> feat: use ngx-fixture custom matchers

- frontend/package.json
- frontend/yarn.lock
This reverts commit 487c40b2878128e1686c645520d93952a8e36925 to avoid
the issue https://github.com/karma-runner/karma/issues/3052
@cexbrayat FYI
> chore(deps): revert update dependency karma to v2.0.3

- frontend/build.gradle.kts
also fix small bug in frontend gradle build
> chore: upgrade yarn and node versions

- frontend/package.json
- frontend/src/app/home/home.component.spec.ts
- frontend/src/app/person-files/person-files.component.spec.ts
- frontend/src/app/person-participations/person-participations.component.spec.ts
- frontend/src/app/search-city.service.spec.ts
- frontend/src/app/tasks-page/tasks-page.component.spec.ts
- frontend/yarn.lock
I still don't understand why the tasks page test didn't pass.
The home component test was needlessly complex.
The person-files component test was wrong.
The person-participations test didn't need to be async.
The search city service tst is clearer this way, IMO.
> fix: upgrade do cli 6.0.8 and fix tests that break

- backend/src/main/kotlin/org/globe42/dao/PersonDaoCustomImpl.kt
- backend/src/main/kotlin/org/globe42/dao/PostalCityDaoCustomImpl.kt
- backend/src/main/kotlin/org/globe42/dao/SpentTimeDaoCustomImpl.kt
- backend/src/main/kotlin/org/globe42/dao/UserDaoCustomImpl.kt
The naming convention for custom repos has been improved in recent spring-data versions.
> refactor: improve custom repo naming

- frontend/src/app/charge-type-edit/charge-type-edit.component.html
- frontend/src/app/charge-type-edit/charge-type-edit.component.spec.ts
- frontend/src/app/confirm.service.ts
- frontend/src/app/error.service.ts
- frontend/src/app/error/error.component.ts
- frontend/src/app/family-resolver.service.ts
- frontend/src/app/navigation-progress/navigation-progress.component.spec.ts
- frontend/src/app/per-unit-revenue-information-resolver.service.ts
- frontend/src/app/person-charge-edit/person-charge-edit.component.html
- frontend/src/app/person-charge-edit/person-charge-edit.component.ts
- frontend/src/app/person-edit/person-edit.component.ts
- frontend/src/app/person-income-edit/person-income-edit.component.html
- frontend/src/app/person-income-edit/person-income-edit.component.spec.ts
- frontend/src/app/person-income-edit/person-income-edit.component.ts
- frontend/src/app/person-network-members/person-network-members.component.html
- frontend/src/app/person-network-members/person-network-members.component.spec.ts
- frontend/src/app/person-participations/person-participations.component.ts
- frontend/src/app/person/person-typeahead.ts
- frontend/src/app/persons/persons.component.ts
- frontend/src/app/task-edit/task-edit.component.html
- frontend/src/app/task-edit/task-edit.component.spec.ts
- frontend/src/app/task-edit/task-edit.component.ts
- frontend/src/app/tasks/tasks.component.spec.ts
also fix default option in select
> refactor: use optional chaining and nullish-coalescing operators

- frontend/angular.json
- frontend/extra-webpack.config.js
- frontend/package.json
- frontend/yarn.lock
also refresh the yarn.lock file
> chore: use custom builders to extend webpack config and remove moment

- frontend/src/app/health-care-coverage/health-care-coverage.component.spec.ts
- frontend/src/app/login/login.component.spec.ts
- frontend/src/app/note/note.component.spec.ts
- frontend/src/app/password-change/password-change.component.spec.ts
- frontend/src/app/person-death/person-death.component.spec.ts
- frontend/src/app/person-layout/person-layout.component.spec.ts
- frontend/src/app/person-notes/person-notes.component.spec.ts
- frontend/src/app/person-wedding-events/person-wedding-events.component.spec.ts
- frontend/src/app/profile/profile.component.spec.ts
- frontend/src/app/spent-time-add/spent-time-add.component.spec.ts
- frontend/src/app/task-edit/task-edit.component.spec.ts
- frontend/src/test.ts
- frontend/src/test/jasmine.config.ts
@cexbrayat FYI
we should do that on our other projects, too.
> refactor: install speculoos matchers once and for all

- frontend/src/app/membership.service.spec.ts
- frontend/src/app/membership.service.ts
- frontend/src/app/person-memberships/person-memberships.component.html
- frontend/src/app/person-memberships/person-memberships.component.spec.ts
- frontend/src/app/person-memberships/person-memberships.component.ts
> feat: allow creating (and deleting) memberships for previous years

- backend/src/main/kotlin/org/globe42/domain/Person.kt
- backend/src/main/kotlin/org/globe42/domain/SchoolLevel.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonCommandDTO.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonController.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonDTO.kt
- backend/src/main/resources/db/migration/V0044__school_level.sql
- backend/src/test/kotlin/org/globe42/dao/MembershipDaoTest.kt
- backend/src/test/kotlin/org/globe42/dao/PersonDaoTest.kt
- backend/src/test/kotlin/org/globe42/dao/TaskDaoTest.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerTest.kt
- frontend/src/app/app.module.ts
- frontend/src/app/display-school-level.pipe.spec.ts
- frontend/src/app/display-school-level.pipe.ts
- frontend/src/app/models/person.command.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person-edit/person-edit.component.html
- frontend/src/app/person-edit/person-edit.component.spec.ts
- frontend/src/app/person-edit/person-edit.component.ts
- frontend/src/app/person/person.component.html
- frontend/src/app/person/person.component.spec.ts
> feat: add school level to person

- backend/src/main/kotlin/org/globe42/dao/ActivityDao.kt
- backend/src/main/kotlin/org/globe42/domain/Activity.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityCommandDTO.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityController.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityDTO.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityTypeController.kt
- backend/src/main/kotlin/org/globe42/web/tasks/TaskController.kt
- backend/src/main/resources/db/migration/V0048__activity.sql
- backend/src/test/kotlin/org/globe42/web/activities/ActivityControllerMvcTest.kt
- frontend/src/app/activities-resolver.service.spec.ts
- frontend/src/app/activities-resolver.service.ts
- frontend/src/app/activities/activities.component.html
- frontend/src/app/activities/activities.component.spec.ts
- frontend/src/app/activities/activities.component.ts
- frontend/src/app/activity-edit/activity-edit.component.html
- frontend/src/app/activity-edit/activity-edit.component.scss
- frontend/src/app/activity-edit/activity-edit.component.spec.ts
- frontend/src/app/activity-edit/activity-edit.component.ts
- frontend/src/app/activity-resolver.service.spec.ts
- frontend/src/app/activity-resolver.service.ts
- frontend/src/app/activity.service.spec.ts
- frontend/src/app/activity.service.ts
- frontend/src/app/activity/activity.component.html
- frontend/src/app/activity/activity.component.spec.ts
- frontend/src/app/activity/activity.component.ts
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/menu/menu.component.html
- frontend/src/app/models/activity.model.ts
- frontend/src/app/participants/participants.component.ts
> feat: activity crud

- backend/src/main/kotlin/org/globe42/dao/ActivityDao.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityController.kt
- backend/src/main/kotlin/org/globe42/web/activities/ActivityReportDTO.kt
- backend/src/test/kotlin/org/globe42/web/activities/ActivityControllerMvcTest.kt
- frontend/src/app/activities-layout/activities-layout.component.html
- frontend/src/app/activities-layout/activities-layout.component.ts
- frontend/src/app/activities/activities.component.html
- frontend/src/app/activities/activities.component.spec.ts
- frontend/src/app/activity-edit/activity-edit.component.html
- frontend/src/app/activity-edit/activity-edit.component.spec.ts
- frontend/src/app/activity-report/activity-report.component.html
- frontend/src/app/activity-report/activity-report.component.spec.ts
- frontend/src/app/activity-report/activity-report.component.ts
- frontend/src/app/activity.service.spec.ts
- frontend/src/app/activity.service.ts
- frontend/src/app/activity/activity.component.html
- frontend/src/app/activity/activity.component.spec.ts
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/models/activity.model.ts
> feat: activity report

- backend/src/main/kotlin/org/globe42/web/persons/PersonController.kt
- backend/src/main/kotlin/org/globe42/web/persons/ReminderDTO.kt
- backend/src/test/kotlin/org/globe42/web/activities/ActivityControllerMvcTest.kt
- backend/src/test/kotlin/org/globe42/web/charges/ChargeCategoryControllerMvcTest.kt
- backend/src/test/kotlin/org/globe42/web/healthcare/HealthCareCoverageControllerMvcTest.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerMvcTest.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerTest.kt
- backend/src/test/kotlin/org/globe42/web/security/AuthenticationTest.kt
- frontend/src/app/app.module.ts
- frontend/src/app/current-person-reminder.service.spec.ts
- frontend/src/app/current-person-reminder.service.ts
- frontend/src/app/current-person.service.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person-death/person-death.component.html
- frontend/src/app/person-death/person-death.component.spec.ts
- frontend/src/app/person-death/person-death.component.ts
- frontend/src/app/person-layout/person-layout.component.html
- frontend/src/app/person-layout/person-layout.component.scss
- frontend/src/app/person-layout/person-layout.component.spec.ts
- frontend/src/app/person-layout/person-layout.component.ts
- frontend/src/app/person-memberships/person-memberships.component.spec.ts
- frontend/src/app/person-memberships/person-memberships.component.ts
- frontend/src/app/person-reminders/person-reminders.component.html
- frontend/src/app/person-reminders/person-reminders.component.spec.ts
- frontend/src/app/person-reminders/person-reminders.component.ts
- frontend/src/app/person-resolver.service.ts
> test: add reminders on person

- backend/src/main/kotlin/org/globe42/dao/MembershipDao.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonController.kt
- backend/src/main/kotlin/org/globe42/web/persons/PersonWithRemindersDTO.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerMvcTest.kt
- backend/src/test/kotlin/org/globe42/web/persons/PersonControllerTest.kt
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/display-reminder-type.pipe.spec.ts
- frontend/src/app/display-reminder-type.pipe.ts
- frontend/src/app/models/person.model.ts
- frontend/src/app/person.service.spec.ts
- frontend/src/app/person.service.ts
- frontend/src/app/persons-layout/persons-layout.component.html
- frontend/src/app/persons-layout/persons-layout.component.spec.ts
- frontend/src/app/persons-with-reminders-resolver.service.spec.ts
- frontend/src/app/persons-with-reminders-resolver.service.ts
- frontend/src/app/persons-with-reminders/persons-with-reminders.component.html
- frontend/src/app/persons-with-reminders/persons-with-reminders.component.spec.ts
- frontend/src/app/persons-with-reminders/persons-with-reminders.component.ts
> feat: add persons with reminders

- backend/src/main/kotlin/org/globe42/web/reports/ReportController.kt
- backend/src/test/kotlin/org/globe42/web/reports/ReportControllerMvcTest.kt
instead of a single one for any French course
> feat: use a column for each French course in appointment report

- frontend/src/app/activities/activities.component.html
- frontend/src/app/activity-report/activity-report.component.html
- frontend/src/app/activity-report/activity-report.component.spec.ts
- frontend/src/app/activity-report/activity-report.component.ts
also make the activities page more readable
> feat: make activity report sortable

- frontend/package.json
- frontend/src/app/validation-defaults/validation-defaults.component.ts
- frontend/yarn.lock
> chore: configure valdemort to throw on missing control

- frontend/.eslintrc.json
- frontend/package.json
- frontend/yarn.lock
> chore: add eslint plugin and rule to ban fdescribe and fit

- backend/src/main/kotlin/org/globe42/dao/NoteDao.kt
- backend/src/main/kotlin/org/globe42/web/mediation/MediationReportDTO.kt
- backend/src/main/kotlin/org/globe42/web/mediation/MediationStatisticsController.kt
- backend/src/main/kotlin/org/globe42/web/reports/ReportController.kt
- backend/src/test/kotlin/org/globe42/dao/NoteDaoTest.kt
- backend/src/test/kotlin/org/globe42/web/mediation/MediationStatisticsControllerMvcTest.kt
- frontend/src/app/app.module.ts
- frontend/src/app/app.routes.ts
- frontend/src/app/mediation-statistics.model.ts
- frontend/src/app/mediation-statistics.service.spec.ts
- frontend/src/app/mediation-statistics.service.ts
- frontend/src/app/mediation-statistics/mediation-statistics.component.html
- frontend/src/app/mediation-statistics/mediation-statistics.component.scss
- frontend/src/app/mediation-statistics/mediation-statistics.component.spec.ts
- frontend/src/app/mediation-statistics/mediation-statistics.component.ts
- frontend/src/app/persons-layout/persons-layout.component.html
- frontend/src/app/persons-layout/persons-layout.component.spec.ts
> feat: add mediation statistics report

- frontend/src/app/menu/menu.component.scss
> refactor: remove workaround
